### ISSUE TITLE
unable to run with current paho-mqtt version (2.0)

### ISSUE THREAD

**Issue by dirstel** [mbs38/spicierModbus2mqtt#28]
current source is unable to run with current paho-mqtt version (2.0) - https://pypi.org/project/paho-mqtt/#history

```
Exception ignored in: <function Client.__del__ at 0x7fa23b524ca0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
Traceback (most recent call last):
  File "modbus2mqtt.py", line 4, in <module>
    main()
  File "/root/spicierModbus2mqtt-master/modbus2mqtt/modbus2mqtt.py", line 427, in main
    asyncio.run(async_main(), debug=False)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/spicierModbus2mqtt-master/modbus2mqtt/modbus2mqtt.py", line 571, in async_main
    mqc=mqtt.Client(client_id=clientid)
TypeError: __init__() missing 1 required positional argument: 'callback_api_version'

```

Quickfix: nail version to 1.6.1 in Dockerfile:
`RUN pip install --root-user-action=ignore --no-cache-dir --upgrade paho-mqtt==1.6.1`

**Comment by Yiivgeny** [comment]
+1

**Comment by ElAmarok** [comment]
doesnt work for me

**Comment by mbs38** [comment]
should be fixed now
