### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by cyrax72** [mbs38/spicierModbus2mqtt#31]
Hi. I run the application like this: 
/home/pi/modbus2mqtt/bin/python3 -m modbus2mqtt --rtu /dev/ttyUSB0 --rtu-baud 9600 --rtu-parity none --mqtt-host localhost --config /home/pi/modbus2mqtt/example.csv

I get this error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pi/modbus2mqtt/lib/python3.11/site-packages/modbus2mqtt/modbus2mqtt.py", line 44, in <module>
    from .addToHomeAssistant import HassConnector
ImportError: attempted relative import with no known parent package

the library versions are as follows:

 /home/pi/modbus2mqtt/bin/pip3 list
Package     Version
----------- -------
future      1.0.0
iso8601     2.1.0
modbus2mqtt 0.72
paho-mqtt   1.6.1
pip         23.0.1
pymodbus    3.7.4
PyYAML      6.0.2
serial      0.0.97
setuptools  66.1.1

Please tell me what is wrong and how to fix it? probably some libraries of the wrong version?

**Comment by mbs38** [comment]
Hi,
sorry I am no longer supporting the addToHomeAssistant option as I am not using Home Assistant anymore. You can, however, add your spicierModbus2mqtt devices in Home Assistant by hand.
